working_directory = "code"

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#262627"

[font]
size = 7

[font.bold]
family = "Fira Code"
style = "Bold"

[font.bold_italic]
family = "Fira Code"
style = "Regular"

[font.glyph_offset]
x = 0
y = 2

[font.italic]
family = "Fira Code"
style = "Light"

[font.normal]
family = "Fira Code"
style = "Medium"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
chars = "\u0002t"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002\u000B"
key = "K"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00021"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00022"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00023"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00024"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00025"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00026"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00027"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00028"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00029"
key = "Key9"
mods = "Command"

[mouse]
hide_when_typing = true

[shell]
args = ["new-session", "-A", "-s", "main"]
program = "/usr/bin/tmux"

[window]
decorations = "none"

[window.padding]
x = 4
y = 4
