" +-------------------+
" | Vim Configuration |
" +-------------------+

"==> Table of Contents
" 1. Syntax and bells
" 2. Files  
" 3. Mappings
" 4. Plugins

" --------------------
"  Chapter 1
"    Syntax and bells
" -------------------->

"==> All the colors
set t_Co=256


"==> Syntax
syntax enable
colorscheme afterglow "TODO where did I pull afterglow from?


"==> Mark lines longer than 80 chacaters

"-> This is a snippet that makes the background red. Looks doable.
highlight OverLength ctermbg=red ctermfg=white guibg=#592929
match OverLength /\%81v./ 

"-> Vim has some functionality for this as well, but it cuts off the lines, so
"   I need to set the textwidth to something big too.
"set colorcolumn=80,160,240
"set textwidth=999999


"==> Bells and mouse

set noerrorbells visualbell t_vb=
set mouse=a


"==> Standard cool Vim things

set nocompatible
filetype plugin on
set wildmenu




"==> Need to find out what this does

hi LineNr ctermbg=bg
hi vertsplit ctermbg=bg ctermfg=bg
hi tab ctermbg=green



"==> Settings for MVim: font and remove bars

set guifont=Fira_Code
set guioptions-=l
set guioptions-=L
set guioptions-=r
set guioptions-=R


"==> Backspace like you're used to

set backspace=indent,eol,start


"==> Use relative linenumbers, but an absolute one for the current line

set relativenumber
set number


"==> Save buffer automatically when closing

"set autowriteall


"==> Tabs as 4 spaces

set tabstop=8
set expandtab
set softtabstop=4
set shiftwidth=4
"set tabstop=8 softtabstop=0 expandtab shiftwidth=4 smarttab



"==> Searching

"-> Search highligh if I want to
nmap <Leader><space> :set hlsearch! hlsearch?<cr>

"-> Incremental search: search as you type (we have fast computers now)
set incsearch

"-> I keep forgetting the search is case sensitive, so ignore
set ignorecase

"-> This makes the search insensitive if you search for lowercase
"   but sensitive if there's a capital in your search somewhere.
set smartcase

"-> But, because this also applies to replacements, I want to be able
"   to toggle it quickly. (https://stackoverflow.com/q/2287440)
nmap <Leader>C :set ignorecase! ignorecase?<cr>



" ----------------------
"  Chapter X
"    Splits and windows
" ---------------------->

"==> Split management

"set splitbelow
"set splitright


"==> Window Management
"-> Normally one would use Ctrl+W and J/K/H/L to navigate from one pane to
"   another, but that's a lot of keystrokes. With these mappings, we only lose
"   the default Ctrl+L for redraw, the rest is unused.

"nmap <C-J> <C-W><C-J>
"nmap <C-K> <C-W><C-K>
"nmap <C-H> <C-W><C-H>
"nmap <C-L> <C-W><C-L>
"-> This is still current, but I now have a plugin that also
"   makes this work with Tmux panes.

" --------------------
"  Chapter 2
"    Files
" -------------------->

"==> Set a recursive fuzzy search

set path+=**


"==> Make it easy to edit config
nmap <Leader>cv :e $MYVIMRC<cr>
nmap <Leader>cp :e ~/.vim/plugins.vim<cr>
nmap <Leader>cs :e ~/.vim/snippets<cr>
nmap <Leader>ct :e ~/.tmux.conf<cr>
nmap <Leader>cz :e ~/.zshrc<cr>
nmap <Leader>c  :e ~/dotfiles<cr>


"==> Toggle NERDTree
nmap <Leader>t :NERDTreeToggle<cr>


"==> I know the thing is called CtrlP but no
let g:ctrlp_map = '<Leader>p'
nmap <Leader>r :CtrlPBufTag<cr>
nmap <Leader>e :CtrlPMRUFiles<cr>

"-> CtrlP ignores
let g:ctrlp_custom_ignore = 'node_modules\DS_Store\|git'
let g:ctrlp_match_window = 'bottom,order:btt,min:1,max:20,results:10'


"==> Leave Netrw alone, NERDTree!
let NERDTreeHijackNetrw = 0


"Tags
nmap <Leader>f :tag<space>


" --------------------
"  Chapter 3
"    Plugins
" -------------------->

"==> Load plugins
so ~/.vim/plugins.vim


" --------------------
"  Chapter 4
"    Mappings
" -------------------->

"==> Quickly access Laravel files
nmap <Leader>lm :!php artisan make:
nmap <Leader>lr  :e routes/web.php<cr>
nmap <Leader>la  :CtrlP<cr>app/
nmap <Leader>lae :CtrlP<cr>app/Exceptions/
nmap <Leader>lac :CtrlP<cr>app/Http/Controllers/
nmap <Leader>lam :CtrlP<cr>app/Models/
nmap <Leader>laj :CtrlP<cr>app/Jobs/
nmap <Leader>lap :CtrlP<cr>app/Providers/
nmap <Leader>las :CtrlP<cr>app/Services/
nmap <Leader>lp  :CtrlP<cr>app/Processors/
nmap <Leader>lc  :CtrlP<cr>config/
nmap <Leader>ld  :CtrlP<cr>database/
nmap <Leader>lj  :CtrlP<cr>resources/assets/js/
nmap <Leader>ls  :CtrlP<cr>resources/assets/sass/
nmap <Leader>lv  :CtrlP<cr>resources/views/
nmap <Leader>lt  :CtrlP<cr>tests/

"==> Quickly access Kirby files
nmap <Leader>kk :!kirby make:
nmap <Leader>kc  :e site/config/config.php<cr>
nmap <Leader>kr  :e site/config/routes.php<cr>
nmap <Leader>ksb :CtrlP<cr>site/blueprints/
nmap <Leader>ksc :CtrlP<cr>site/controllers/
nmap <Leader>ksm :CtrlP<cr>site/models/
nmap <Leader>ksp :CtrlP<cr>site/plugins/
nmap <Leader>kss :CtrlP<cr>site/snippets/
nmap <Leader>ksg :CtrlP<cr>site/tags/
nmap <Leader>kst :CtrlP<cr>site/templates/
nmap <Leader>ksu :CtrlP<cr>site/accounts/

"--- Macros
let @a="yiw/|^MO$this->^[pa = $^[pa;^[?construct^MOprotected $^[pa^M^[/construct^M/^R\"^M, "

"---- PHP dingen
function! IPhpInsertUse()
    call PhpInsertUse()
    call feedkeys('a', 'n')
endfunction
autocmd FileType php inoremap <Leader>n <Esc>:call IPhpInsertUse()<CR>
autocmd FileType php noremap <Leader>n :call PhpInsertUse()<CR>

function! IPhpExpandClass()
    call PhpExpandClass()
    call feedkeys('a', 'n')
endfunction
autocmd FileType php inoremap <Leader>nf <Esc>:call IPhpExpandClass()<CR>
autocmd FileType php noremap <Leader>nf :call PhpExpandClass()<CR>



"---- Plugins settings


"-- greplace
set grepprg=ag
let g:grep_cmd_opts = '--line-numbers --noheading'

"-- PHP CS fixer
let g:php_cs_fixer_level = 'PSR-2'
nnoremap <silent><leader>pf :call PhpCsFixerFixFile()<cr>

"-- PDV - docblocks voor PHP
let g:pdv_template_dir = $HOME ."/.vim/bundle/pdv/templates_snip"
nnoremap <Leader>d :call pdv#DocumentWithSnip()<cr>

"-- Ultisnips
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<tab>"
let g:UltiSnipsJumpBackwardTrigger="<s-tab>"



"---- Auto Commands

"==> Source the .vimrc-file once when we save it
augroup autosourcing
    autocmd!
    autocmd BufWritePost .vimrc source %
augroup END


" Notes and tips
"
" gg = bovenaan file
" G  = onderaan file
"
" zz = zet cursor in het midden
"
" v/d + i/a + ( = selecteer/delete alles tussen de haakjes
"
" Rebuild_index: `ctags -R`
"  `,f` / `:tag` om te zoeken
"  :tn = tag next
"  :tp = tag previous
"  :ts = lijst van alle tags
"  Ctrl+] = ga naar declaratie van functie
"  Ctrl+^ = ga terug naar laatste edit
"
" Zoeken:
" /iets<enter>
" daarna `n` voor de volgende plek
