#!/usr/bin/env bash

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

leftwm-command "UnloadTheme"

pkill picom
pkill polybar
pkill xbanish

# Killing Redshift hard and resetting the screen
# makes sure sure there is no gitching fading
# when I reload the LeftWM configuration.
pkill -KILL redshift
redshift -oxP
