#!/usr/bin/env bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

# set the theme.ron config
leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

# boot if it exists
if [ -x "$(command -v picom)" ]; then
  # Picom for some transparency
  picom &> /dev/null &
fi
if [ -x "$(command -v feh)" ]; then
  # Feh for the backgroudn image
  feh --bg-scale /usr/share/backgrounds/gnome/keys-d.jpg &> /dev/null &
fi
if [ -x "$(command -v redshift)" ]; then
  # Redshift for making my screen more red at night
  redshift -l $(curl -s "https://location.services.mozilla.com/v1/geolocate?key=geoclue" | jq -r '"\(.location.lat):\(.location.lng)"') &> /dev/null &
fi
if [ -x "$(command -v ibus-daemon)" ]; then
  # ibus so I can pick the 'English (Macintosh)' keyboard and
  # have my familiar Alt codes, but with AltGr.
  ibus-daemon -rxRd
fi

index=0
monitors="$(polybar -m | sed s/:.*//)"
leftwm-state -q -n -t $SCRIPTPATH/sizes.liquid | sed -r '/^\s*$/d' | while read -r width x y
do
  let indextemp=index+1
  monitor=$(sed "$indextemp!d" <<<"$monitors")
  barname="mainbar$index"
  monitor=$monitor offset=$x width=$width polybar -c $SCRIPTPATH/polybar.config $barname &> /dev/null &
  let index=indextemp
done
