# === Definitions ===

# Path to oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Path to my dotfiles
export DOTFILES="$HOME/dotfiles"


# === Paths ===

# For Ruby things
export PATH="$HOME/.gem/bin:$PATH"

# Then local composer and global composer
export PATH="vendor/bin:$HOME/.composer/vendor/bin:$PATH"

# But start with ~/bin, dotfiles and Homebrew
export PATH="$HOME/bin:$DOTFILES/bin:/usr/local/bin:$PATH"


# === ZSH ===

# Plugins
plugins=(git osx laravel5)

# Load oh-my-zsh
source $ZSH/oh-my-zsh.sh

# Load my own prompt
source $DOTFILES/zsh/prompt.zsh

# Load aliases
source $DOTFILES/zsh/aliases.zsh

# Set language environment 
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='subl'
fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Easy ZSH config edit
alias zshconf="vim ~/.zshrc && source ~/.zshrc"
alias reload="source ~/.zshrc"

