# === Definitions ===

# Path to oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Path to my dotfiles
export DOTFILES="$HOME/dotfiles"


# === Paths ===

# For Ruby things
export PATH="$HOME/.gem/bin:$PATH"

# Then local composer and global composer
export PATH="vendor/bin:$HOME/.composer/vendor/bin:$PATH"

# But start with ~/bin, dotfiles and Homebrew
export PATH="$HOME/bin:$DOTFILES/bin:/usr/local/bin:$PATH"


# === ZSH ===

# Plugins
plugins=(git osx laravel5 vi-mode)

# Load oh-my-zsh
source $ZSH/oh-my-zsh.sh

# Load my own prompt
source $DOTFILES/zsh/prompt.zsh

# Set language environment
# export LANG=en_US.UTF-8

# Colors for folders and the like
export LSCOLORS='Axfxcxdxbxegedabagacad'

# Preferred editor
export EDITOR='vim'

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# fix arrows in tmux
bindkey '^R' history-incremental-search-backward
bindkey -v

# === apps ===

# some commands for easy journaling
source $DOTFILES/todo/aliases.zsh


# === aliases ===

# Easy ZSH config edit
alias zshconf="vim ~/.zshrc && source ~/.zshrc"
alias reload="source ~/.zshrc"
alias dotfiles="cd $DOTFILES && git fetch && git status -sb"

# I keep doing this
alias :q="exit"

source $DOTFILES/git/aliases.zsh
source $DOTFILES/laravel/aliases.zsh
source $DOTFILES/macos/aliases.zsh
source $DOTFILES/php/aliases.zsh
source $DOTFILES/tmux/aliases.zsh

# Better searching in command mode
bindkey -M vicmd '?' history-incremental-search-backward
bindkey -M vicmd '/' history-incremental-search-forward

# Beginning search with arrow keys
bindkey "^[OA" up-line-or-beginning-search
bindkey "^[OB" down-line-or-beginning-search
bindkey -M vicmd "k" up-line-or-beginning-search
bindkey -M vicmd "j" down-line-or-beginning-search
